# Copyright (c) 2024-2026, The UW Lab Project Developers.
# SPDX-License-Identifier: BSD-3-Clause
"""Render the partial-assembly spawn: place the leg from ``partial_assemblies.pt`` against the
live fixture and photograph the result, plus a close-up on the bore.

WHY. ``resets_ObjectPartiallyAssembledEEGrasped.pt`` in the production pair directory is NOT a
partial-assembly bank -- it was generated by the same ``scale_only.sh`` recipe as the Resting bank
with only ``--reset_type`` (the output FILENAME) changed, and ``DEXLIFT_PARTIAL_ASSEMBLY`` is set
in no script in this tree. Its legs sit a median 0.26 m from the fixture. The real machinery is
``partial_assemblies.pt`` + ``reset_insertive_object_from_partial_assembly_dataset``, and it had
never been rendered, so nobody had looked at what it actually spawns.

WHAT THIS EXERCISES. The same composition the event does, via the same call:

    T_leg_world = combine_frame_transforms(T_fixture_world, rel_pos, rel_quat)

read off the LIVE fixture pose after ``env.reset()``, not off a config literal -- so a fixture the
reset moved is followed. No settle: this photographs the SPAWN, which is what the event specifies.
Under ``ObjectPartiallyAssembledEEGrasped`` the hand holds the leg there; under the EEAnywhere
sibling an unsupported leg would simply fall, and that would be a fact about gravity rather than
about the dataset.

THE GEOMETRY IT MEASURES, per state, in the FIXTURE's own frame, all derived rather than assumed:

    tip   = rel_pos + quat_apply(rel_quat, leg.assembled_offset.pos)
    seat  = fixture.assembled_offset.pos          (the fitted bore axis, UWLab-3o5.13)
    dxy   = |tip.xy - seat.xy|                    lateral miss from the bore axis
    dz    = tip.z - seat.z                        height above fully-seated (0 = seated)
    tilt  = angle between quat_apply(rel_quat, -X_leg) and world -Z

The bore's tightest wall gives ~0.93 mm of genuine clearance against the leg's 10.004 mm flat
pilot, so a state with dxy above ~1 mm cannot have its tip inside the hole however small dz is --
it is resting on the collar rim or hanging beside it. Both numbers are printed per state and
burned into the summary so the picture and the measurement cannot drift apart.

CONTROLS, and they are the whole reason this render can be trusted. A photograph of a leg NOT in a
hole is ambiguous between three very different claims: the dataset does not seat the leg; the
fixture has no usable hole; or the seat constant this script measures against is wrong. Two extra
frames separate them, and both are rendered before the dataset strip:

  BORE EMPTY       the leg parked far away, camera on the seat. Shows the hole exists and where.
  FULLY ASSEMBLED  the leg placed at the pose the METADATA says is assembled, composed exactly the
                   way ``assembly_sampling_event`` composes it --
                       target = fixture_pose o fixture.assembled_offset      (Offset.combine)
                       leg    = target o inv(leg.assembled_offset)           (Offset.subtract)
                   -- through the production ``Offset`` class, not a hand-rolled inverse. Upstream
                   hand-rolled this and rotated offset_pos by the TARGET quat instead of the
                   OUTPUT quat, which is correct only for an identity offset quat; ours is Ry(+90),
                   so that error would be ~150 mm here.

If the leg visibly seats in the FULLY ASSEMBLED frame and the dataset strip does not, the geometry
is sound and the dataset is the problem. That is the distinction being tested.

The four configuration facts this scene needs are the same four documented in
``render_reset_states_viewport.py``; see that module's docstring.
"""

from __future__ import annotations

import argparse
import time
from pathlib import Path

from isaaclab.app import AppLauncher

parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("--partial-assemblies", type=Path, required=True)
parser.add_argument("--task", default="OmniReset-UR5eDelto-ObjectRestingEEGrasped-v0")
parser.add_argument("--dataset-dir", default="./Datasets_render/OmniReset")
parser.add_argument("--insertive-variant", default="leg200mm")
parser.add_argument("--receptive-variant", default="onelegfixture")
parser.add_argument("--out", type=Path, default=Path("artifacts/partial_assemblies"))
parser.add_argument("--count", type=int, default=8)
parser.add_argument("--width", type=int, default=960)
parser.add_argument("--height", type=int, default=720)
parser.add_argument("--drop-terminations", nargs="*", default=["success"])
parser.add_argument("--light-intensity", type=float, default=1000.0,
                    help="dome light intensity; reset_states_cfg ships 10000 while the TRAINING"
                         " scene uses 1000, and 10x is what washed earlier frames out.")
parser.add_argument("--leg-tip-offset", type=float, nargs=3, default=[-0.106203, 0.0, 0.0],
                    help="leg assembled_offset.pos -- the TIP in the leg's own mesh frame.")
parser.add_argument("--bore-seat", type=float, nargs=3, default=[-0.056250, 0.056250, -0.009374],
                    help="fixture assembled_offset.pos -- the fitted bore axis and seat depth.")
parser.add_argument("--hide-robot", action="store_true", default=True,
                    help="park the arm away from the bore. The subject here is the leg/fixture"
                         " geometry, and an EE-anywhere arm lands in front of it often enough to"
                         " occlude the one thing the frame exists to show.")
parser.add_argument("--leg-tip-quat", type=float, nargs=4, default=[0.70710678, 0.0, 0.70710678, 0.0],
                    help="leg assembled_offset.quat, (w,x,y,z). Only used by the two CONTROL frames.")
parser.add_argument("--no-controls", action="store_true",
                    help="skip the two control frames. Do not: without them a reader cannot tell"
                         " 'this dataset does not seat the leg' from 'this fixture has no hole'"
                         " or 'the seat constant is wrong'. See the CONTROLS note in the docstring.")
AppLauncher.add_app_launcher_args(parser)
args = parser.parse_args()
args.enable_cameras = True

import torch  # noqa: E402

# ---- everything decidable WITHOUT Isaac is decided before Isaac launches ------------------------
pa = torch.load(args.partial_assemblies, map_location="cpu")
rel_pos = pa["relative_position"].float()
rel_quat = pa["relative_orientation"].float()
n_total = rel_pos.shape[0]
if rel_quat.shape[0] != n_total:
    raise SystemExit(f"[pa] REFUSING: {n_total} positions vs {rel_quat.shape[0]} quaternions")


def _quat_apply(q: torch.Tensor, v: torch.Tensor) -> torch.Tensor:
    """(w,x,y,z) scalar-first, matching this codebase's convention everywhere else."""
    u = q[..., 1:]
    t = 2.0 * torch.cross(u, v, dim=-1)
    return v + q[..., 0:1] * t + torch.cross(u, t, dim=-1)


LEG_TIP = torch.tensor(args.leg_tip_offset)
SEAT = torch.tensor(args.bore_seat)
tip = rel_pos + _quat_apply(rel_quat, LEG_TIP.expand_as(rel_pos))
dxy = torch.linalg.norm(tip[:, :2] - SEAT[:2], dim=1)
dz = tip[:, 2] - SEAT[2]
axis = _quat_apply(rel_quat, torch.tensor([-1.0, 0.0, 0.0]).expand_as(rel_pos))
tilt = torch.rad2deg(torch.arccos((-axis[:, 2]).clamp(-1.0, 1.0)))

print(f"[pa] {n_total} stored partial assemblies", flush=True)
print(f"[pa] lateral miss from bore axis (mm): p50 {dxy.median()*1e3:.3f}  max {dxy.max()*1e3:.3f}", flush=True)
print(f"[pa] height above seat      (mm): p50 {dz.median()*1e3:.2f}  min {dz.min()*1e3:.2f}  max {dz.max()*1e3:.2f}", flush=True)
print(f"[pa] tilt from vertical    (deg): p50 {tilt.median():.2f}  max {tilt.max():.2f}", flush=True)

# SELECT ACROSS THE RANGE, NOT THE FLATTERING END. An engagement score orders the bank from
# most-inserted to least; sampling that order at even quantiles shows the best case, the median
# and the worst case in one strip. Picking the best N would photograph a dataset that does not
# exist.
score = dxy + torch.clamp(dz, min=0.0) + torch.deg2rad(tilt) * 0.05
order = torch.argsort(score)
k = min(args.count, n_total)
sel = [int(order[round(i * (n_total - 1) / max(k - 1, 1))].item()) for i in range(k)]
print(f"[pa] selected (best->worst by engagement): {sel}", flush=True)

t0 = time.time()
app = AppLauncher(args).app
print(f"[pa] app up {time.time()-t0:.1f}s", flush=True)

import gymnasium as gym  # noqa: E402
import isaaclab.utils.math as math_utils  # noqa: E402
import numpy as np  # noqa: E402
import uwlab_tasks  # noqa: F401,E402
from isaaclab_tasks.utils import parse_env_cfg  # noqa: E402
from PIL import Image  # noqa: E402

cfg = parse_env_cfg(args.task, device=args.device, num_envs=1)
for term in args.drop_terminations:
    if getattr(cfg.terminations, term, None) is not None:
        setattr(cfg.terminations, term, None)
        print(f"[pa] dropped termination '{term}'", flush=True)

cfg.scene.insertive_object = cfg.variants["scene.insertive_object"][args.insertive_variant]
cfg.scene.receptive_object = cfg.variants["scene.receptive_object"][args.receptive_variant]

patched = 0
for name, term in vars(cfg.events).items():
    if term is not None and getattr(term, "params", None) and "dataset_dir" in term.params:
        term.params["dataset_dir"] = args.dataset_dir
        patched += 1
if patched == 0:
    raise SystemExit("[pa] REFUSING: no event term takes dataset_dir; the override would be a silent no-op")

cfg.scene.num_envs = 1
cfg.sim.render_interval = 1
cfg.sim.physx.gpu_collision_stack_size = 256 * 1024 * 1024
if getattr(cfg.scene, "sky_light", None) is not None and hasattr(cfg.scene.sky_light.spawn, "intensity"):
    cfg.scene.sky_light.spawn.intensity = args.light_intensity
cfg.viewer.resolution = (args.width, args.height)
cfg.viewer.origin_type = "world"

t = time.time()
env = gym.make(args.task, cfg=cfg, render_mode="rgb_array").unwrapped
print(f"[pa] gym.make {time.time()-t:.1f}s", flush=True)
env.reset()
frame = env.render()
if frame is None:
    raise SystemExit("[pa] REFUSING: render() returned None -- render_mode is not rgb_array")

args.out.mkdir(parents=True, exist_ok=True)
leg = env.scene["insertive_object"]
fixture = env.scene["receptive_object"]
robot = env.scene["robot"]

if args.hide_robot:
    # Fold the arm back to its default posture. It is not part of what this render claims, and an
    # EE-anywhere reset regularly parks it between the camera and the bore.
    q0 = robot.data.default_joint_pos.clone()
    robot.write_joint_state_to_sim(q0, torch.zeros_like(q0))
    robot.set_joint_position_target(q0)
    env.scene.write_data_to_sim()
    env.sim.forward()

fx_pos = fixture.data.root_pos_w[0:1].clone()
fx_quat = fixture.data.root_quat_w[0:1].clone()
seat_w = fx_pos + _quat_apply(fx_quat, SEAT.unsqueeze(0).to(env.device))
print(f"[pa] fixture world pos {[round(v,4) for v in fx_pos[0].tolist()]}", flush=True)
print(f"[pa] bore seat world   {[round(v,4) for v in seat_w[0].tolist()]}", flush=True)


def shoot(stem: str) -> None:
    """Two views of whatever the leg currently is: wide, and tight on the fitted bore axis."""
    s = seat_w[0].tolist()
    views = {
        # Wide: the whole leg against the fixture, so the pose reads as a pose.
        "wide": ([s[0] + 0.42, s[1] - 0.34, s[2] + 0.30], [s[0], s[1], s[2] + 0.09]),
        # Close: tight on the bore. This is the view that shows engagement or its absence, and it
        # is aimed at the FITTED bore axis rather than at the leg, so a leg that misses the hole
        # is visibly off-centre instead of being re-centred by the camera.
        "bore": ([s[0] + 0.13, s[1] - 0.11, s[2] + 0.055], list(s)),
    }
    for vname, (veye, vtarget) in views.items():
        env.sim.set_camera_view(tuple(veye), tuple(vtarget))
        env.sim.render()
        Image.fromarray(np.asarray(env.render())[:, :, :3]).save(args.out / f"{stem}_{vname}.png")


def place_leg(pos_w: torch.Tensor, quat_w: torch.Tensor) -> None:
    leg.write_root_pose_to_sim(torch.cat([pos_w, quat_w], dim=-1))
    leg.write_root_velocity_to_sim(torch.zeros((1, 6), device=env.device))
    env.scene.write_data_to_sim()
    env.sim.forward()


if not args.no_controls:
    # CONTROL 1 -- BORE EMPTY. Park the leg a metre up and out; the seat camera then shows the
    # hole itself, which is what makes "the leg is not in it" a readable statement.
    place_leg(
        (fx_pos + torch.tensor([0.0, 0.0, 1.0], device=env.device)),
        torch.tensor([[1.0, 0.0, 0.0, 0.0]], device=env.device),
    )
    shoot("control_00_bore_empty")
    print("[pa] control: BORE EMPTY rendered", flush=True)

    # CONTROL 2 -- FULLY ASSEMBLED, through the production Offset class, never a hand-rolled inverse.
    from uwlab_tasks.manager_based.manipulation.omnireset.assembly_keypoints import Offset  # noqa: E402

    fixture_off = Offset(pos=tuple(args.bore_seat), quat=(1.0, 0.0, 0.0, 0.0))
    leg_off = Offset(pos=tuple(args.leg_tip_offset), quat=tuple(args.leg_tip_quat))
    tgt_pos, tgt_quat = fixture_off.combine(fx_pos, fx_quat)
    asm_pos, asm_quat = leg_off.subtract(tgt_pos, tgt_quat)
    place_leg(asm_pos, asm_quat)
    tip_w = leg.data.root_pos_w[0:1] + _quat_apply(leg.data.root_quat_w[0:1], LEG_TIP.unsqueeze(0).to(env.device))
    c_dxy = float(torch.linalg.norm((tip_w - seat_w)[0, :2]).item())
    c_dz = float((tip_w - seat_w)[0, 2].item())
    c_axis = _quat_apply(leg.data.root_quat_w[0:1], torch.tensor([[-1.0, 0.0, 0.0]], device=env.device))
    c_tilt = float(torch.rad2deg(torch.arccos((-c_axis[0, 2]).clamp(-1.0, 1.0))).item())
    shoot("control_01_fully_assembled")
    print(f"[pa] control: FULLY ASSEMBLED  lateral={c_dxy*1e3:.4f}mm above_seat={c_dz*1e3:.4f}mm "
          f"tilt={c_tilt:.4f}deg", flush=True)
    # This is a closed loop -- the seat is where the composition puts it -- so it can only fail if
    # the Offset algebra or the metadata is internally inconsistent. That is exactly what it guards.
    if c_dxy > 1e-4 or abs(c_dz) > 1e-4 or c_tilt > 0.05:
        print("[pa] WARNING: the assembled control does NOT land on its own seat -- the metadata"
              " offsets or the Offset algebra disagree with each other", flush=True)

rows = []
for ordinal, idx in enumerate(sel, start=1):
    # THE EVENT'S OWN COMPOSITION, through the same library call it uses:
    #   T_leg_world = T_fixture_world o T_relative
    leg_pos_w, leg_quat_w = math_utils.combine_frame_transforms(
        fx_pos,
        fx_quat,
        rel_pos[idx].unsqueeze(0).to(env.device),
        rel_quat[idx].unsqueeze(0).to(env.device),
    )
    place_leg(leg_pos_w, leg_quat_w)

    # Re-derive the tip IN WORLD from what the simulator now holds, rather than trusting the
    # pre-Isaac arithmetic. If the two disagree, the composition is wrong and the picture is lying.
    tip_w = leg.data.root_pos_w[0:1] + _quat_apply(leg.data.root_quat_w[0:1], LEG_TIP.unsqueeze(0).to(env.device))
    live_dxy = float(torch.linalg.norm((tip_w - seat_w)[0, :2]).item())
    live_dz = float((tip_w - seat_w)[0, 2].item())
    drift = abs(live_dxy - float(dxy[idx])) + abs(live_dz - float(dz[idx]))
    if drift > 1e-3:
        print(f"[pa] WARNING state {idx}: live geometry differs from stored by {drift*1e3:.2f} mm", flush=True)

    stem = f"pa_{ordinal:02d}_idx{idx}_dxy{live_dxy*1e3:.1f}mm_dz{live_dz*1e3:.1f}mm_tilt{tilt[idx]:.1f}deg"
    shoot(stem)

    rows.append((ordinal, idx, live_dxy * 1e3, live_dz * 1e3, float(tilt[idx])))
    print(f"[pa] state {ordinal}/{len(sel)} idx={idx} lateral={live_dxy*1e3:.3f}mm "
          f"above_seat={live_dz*1e3:.2f}mm tilt={tilt[idx]:.2f}deg", flush=True)

print("\n[pa] SUMMARY  (lateral = miss from the fitted bore axis; clearance is ~0.93 mm)", flush=True)
for ordinal, idx, a, b, c in rows:
    engaged = "IN BORE" if (a < 0.93 and -0.1 <= b < 4.0) else "not engaged"
    print(f"[pa]  {ordinal:2d} idx={idx:4d}  lateral {a:7.3f} mm  above seat {b:7.2f} mm  tilt {c:5.2f} deg  {engaged}", flush=True)
n_eng = sum(1 for _, _, a, b, _ in rows if a < 0.93 and -0.1 <= b < 4.0)
print(f"[pa] engaged {n_eng}/{len(rows)} of the RENDERED strip", flush=True)
whole = int((((dxy < 0.00093) & (dz >= -1e-4) & (dz < 0.004)).sum()).item())
print(f"[pa] engaged {whole}/{n_total} of the WHOLE dataset", flush=True)
print("[pa] RENDER_OK", flush=True)

# Isaac's shutdown hangs on this scene routinely; every frame is already on disk.
import os as _os  # noqa: E402
import sys as _sys  # noqa: E402

_sys.stdout.flush()
_sys.stderr.flush()
_os._exit(0)
